### ISSUE TITLE
Robot models in unit tests

### ISSUE THREAD

**Issue by nim65s** [humanoid-path-planner/hpp-core#128]
Hi,

For the records some tests need robot descriptions:
- test-continuous-collision-checking needs ur
- split-path needs romeo
- problem needs baxter

So for now, the CI is not passing for those tests.

Ref https://github.com/stack-of-tasks/pinocchio/issues/546

**Comment by florent-lamiraux** [comment]
What about adding dependencies to
  - ur_description,
  - romeo_description,
  - hpp-environments (for baxter)
when tests are activated ?

**Comment by nim65s** [comment]
The  [ur_description](https://github.com/ros-industrial/universal_robot/tree/kinetic-devel/ur_description/urdf) package do not provide URDF, but xacros ; so we either need to add xacro as a dependency too, and add some machinery in the cmake submodule to call xacro, or we would need a direct access to URDFs.

It might be a similar issue for the other.

**Comment by florent-lamiraux** [comment]
I forgot about this point.
romeo_description and hpp_environments both provide urdf file. Only ur_description raises the issue.
One solution is to remove dependency to "hpp-corbaserver" in hpp_universal_robot and to add a dependency to "hpp_universal_robots" in hpp-core if the test are enabled.

**Comment by nim65s** [comment]
hpp-environments also depends on hpp-corbaserver: 
https://github.com/humanoid-path-planner/hpp-environments/blob/master/package.xml#L11
So we would also have to remove this.

I would prefer to create a repo / package with all the robot descriptions (urdf, srdf, meshes) that all the team needs, and without any dependency to anything else. It could gather files from romeo_description, hpp_universal_robot, hpp-environments, etc. and be a dependency to those packages instead

This is the solution we are currently seeking in Pinocchio. What do you think about it ?

**Comment by florent-lamiraux** [comment]
It does not seem to me this solution is scalable.

**Comment by jmirabel** [comment]
This has its drawbacks too. The package would be very big and hard to maintain.

**Comment by nim65s** [comment]
After discussions, I will:
- remove hpp-corbaserver dependency from hpp-baxter & hpp-universal-robot
- add hpp-baxter, hpp-universal-robot & romeo_description as compile dependencies in hpp-core if the tests are enabled

**Comment by florent-lamiraux** [comment]
The model of baxter used in test "problem.cc" is in hpp_environments:
https://raw.githubusercontent.com/humanoid-path-planner/hpp-pinocchio/master/src/simple-device.cc

**Comment by jmirabel** [comment]
I think this has been addressed. Re-open if not.
