### ISSUE TITLE
Bug in WeighedDistance with a carlike robot

### ISSUE THREAD

**Issue by florent-lamiraux** [humanoid-path-planner/hpp-core#160]
Commit 8ac3f71 in git@github.com:florent-lamiraux/hpp-core adds a unit test that makes the weighed distance fail.

**Comment by jmirabel** [comment]
See my comment here: https://github.com/florent-lamiraux/hpp-core/commit/3f4802106c0c9dc8c975d3f3788f622011fb1bd5#r32820313

**Comment by florent-lamiraux** [comment]
You are right. Thank you.
