### ISSUE TITLE
Bug in SplineGradientBased

### ISSUE THREAD

**Issue by jmirabel** [humanoid-path-planner/hpp-core#190]
I report here a bug which was originally reported by @olivier-roussel.

The SplineGradientBased method runs into a SEGV.

**Comment by jmirabel** [comment]
A dirty fix to avoid the SEGV is to add
```cpp
if(R.cols() == 0)
  throw std::invalid_argument("Got 0 columns R matrix");
```
before line https://github.com/humanoid-path-planner/hpp-core/blob/90c1e87fa52bb4bd26e26d1a57459e0f1c18d345/src/path-optimization/spline-gradient-based/eiquadprog_2011.hpp#L549

**Comment by nim65s** [comment]
Couldn't we use http://github.com/gepetto/eiquadprog ?

**Comment by olivier-roussel** [comment]
This was just to at least "catch" to avoid SEGV, but the optimization will be left unsolved.

What I got is a call to the QP solver with 0 size H matrix and null rank collisionReduced matrix

**Comment by olivier-roussel** [comment]
So not related to the QP solver to me, instead it looks like a bug in spline-gradient-based

**Comment by jmirabel** [comment]
@olivier-roussel Could you try the following:
- Verify that the issue happens at this line: https://github.com/humanoid-path-planner/hpp-core/blob/90c1e87fa52bb4bd26e26d1a57459e0f1c18d345/src/path-optimization/spline-gradient-based.cc#L540
- Adding `if(b.size() == 0) throw std::invalid_argument("Got an empty b vector");` before https://github.com/humanoid-path-planner/hpp-core/blob/90c1e87fa52bb4bd26e26d1a57459e0f1c18d345/src/path-optimization/quadratic-program.cc#L65

**Comment by olivier-roussel** [comment]
This workarround seems to solve the problem on my side, but I let @jmirabel check if it makes sense and if it catch everything...

>diff --git a/src/path-optimization/spline-gradient-based.cc b/src/path-optimization/spline-gradient-based.cc
>index 7c39cc8..15d59dc 100644
>--- a/src/path-optimization/spline-gradient-based.cc
>+++ b/src/path-optimization/spline-gradient-based.cc
>@@ -537,6 +537,10 @@ namespace hpp {
>                 computeInterpolatedSpline = true;
>               } else {
>                if(QPc.H.rows() == 0 and collisionReduced.rank == 0)
>                {
>                  break;
>                }
>                 QPc.solve(collisionReduced, boundConstraintReduced);
>                 bool overConstrained = (QPc.H.rows() < collisionReduced.rank);
>                 if (overConstrained) {

**Comment by olivier-roussel** [comment]
> @olivier-roussel Could you try the following:
> 
>     * Verify that the issue happens at this line: https://github.com/humanoid-path-planner/hpp-core/blob/90c1e87fa52bb4bd26e26d1a57459e0f1c18d345/src/path-optimization/spline-gradient-based.cc#L540
> 
>     * Adding `if(b.size() == 0) throw std::invalid_argument("Got an empty b vector");` before https://github.com/humanoid-path-planner/hpp-core/blob/90c1e87fa52bb4bd26e26d1a57459e0f1c18d345/src/path-optimization/quadratic-program.cc#L65

Ok will try that

**Comment by jmirabel** [comment]
From your answers, I think I understood the issue. I will propose a patch.

**Comment by olivier-roussel** [comment]
> @olivier-roussel Could you try the following:
> 
>     * Adding `if(b.size() == 0) throw std::invalid_argument("Got an empty b vector");` before https://github.com/humanoid-path-planner/hpp-core/blob/90c1e87fa52bb4bd26e26d1a57459e0f1c18d345/src/path-optimization/quadratic-program.cc#L65

I indeed catch this exception (without the workarround I proposed before of course).

**Comment by jmirabel** [comment]
Does the following patch work ?

```
diff --git a/src/path-optimization/spline-gradient-based.cc b/src/path-optimization/spline-gradient-based.cc
index 7c39cc8..8cad2e7 100644
--- a/src/path-optimization/spline-gradient-based.cc
+++ b/src/path-optimization/spline-gradient-based.cc
@@ -455,6 +455,9 @@ namespace hpp {
 #endif // NDEBUG
 
         QuadraticProgram QPc (QP, constraint);
+        if (QPc.H.rows() == 0)
+          // There are no variables left for optimization.
+          return this->buildPathVector (splines);
         QPc.computeLLT();
         QPc.solve(collisionReduced, boundConstraintReduced);
 
```

**Comment by jmirabel** [comment]
> Couldn't we use [http://github.com/gepetto/eiquadprog](https://github.com/gepetto/eiquadprog) ?

your link is broken. Could you update it ?

**Comment by olivier-roussel** [comment]
> Does the following patch work ?
> 
> ```
> diff --git a/src/path-optimization/spline-gradient-based.cc b/src/path-optimization/spline-gradient-based.cc
> index 7c39cc8..8cad2e7 100644
> --- a/src/path-optimization/spline-gradient-based.cc
> +++ b/src/path-optimization/spline-gradient-based.cc
> @@ -455,6 +455,9 @@ namespace hpp {
>  #endif // NDEBUG
>  
>          QuadraticProgram QPc (QP, constraint);
> +        if (QPc.H.rows() == 0)
> +          // There are no variables left for optimization.
> +          return this->buildPathVector (splines);
>          QPc.computeLLT();
>          QPc.solve(collisionReduced, boundConstraintReduced);
>  
> ```

Yes, this is working and solved the bug in this test case. Thanks a lot.

**Comment by nim65s** [comment]
my bad: https://github.com/stack-of-tasks/eiquadprog

**Comment by jmirabel** [comment]
@nim65s this package is nice but lacks one important thing. There are several versions of eiQuadProg. Is there a place where the difference between the versions is explained ?

**Comment by jmirabel** [comment]
I close this as the main issue has been addressed. @nim65s the point I raised might be better placed in the package you mentioned.

**Comment by nim65s** [comment]
The point is exactly that there are several version of this, and I think we should focus on using one external source, or maintain our own, but in one main place.

This one is correctly tested: https://gepettoweb.laas.fr/doc/stack-of-tasks/eiquadprog/master/coverage/, so I think it is a good candidate.

**Comment by jmirabel** [comment]
My point wasn't clear then. I mean that within https://github.com/stack-of-tasks/eiquadprog, there are 3 versions of eiquadprog: https://github.com/stack-of-tasks/eiquadprog/tree/master/include/eiquadprog.
