### ISSUE TITLE
ProjectionError report as PathValidationError

### ISSUE THREAD

**Issue by jmirabel** [humanoid-path-planner/hpp-core#209]
When the projection fails in the path validation procedures, the path validation report is empty. We should add a projection error struct and use it at least in:
https://github.com/humanoid-path-planner/hpp-core/blob/29acc2d7947e45c36be738e82ca1e61c01be2882/src/path-validation/discretized.cc#L54
https://github.com/humanoid-path-planner/hpp-core/blob/29acc2d7947e45c36be738e82ca1e61c01be2882/src/continuous-validation/progressive.cc#L91
https://github.com/humanoid-path-planner/hpp-core/blob/29acc2d7947e45c36be738e82ca1e61c01be2882/src/continuous-validation/dichotomy.cc#L72

**Comment by florent-lamiraux** [comment]
I agree.
