### ISSUE TITLE
Unit test relative motion

### ISSUE THREAD

**Issue by jmirabel** [humanoid-path-planner/hpp-core#219]
With the current devel branch, test relative-motion fails at line:
https://github.com/humanoid-path-planner/hpp-core/blob/3c5a0115cca66ad34e5ecf232e5c5b64e0bc869a/tests/relative-motion.cc#L219

In the relative motion matrix, it is now Constrained, while it was Parameterized before. The relation between the two joint is constrained by an explicit relative pose constraint.

I can fix the unit test. This will not influence the collision validation. However, this means that the constraint became non-parameterized by default and that it was parameterized before. I think here it should be non-parameterized since no "Equality" was passed to the constructor of RelativePose::create. This comes from commit ac567f56. @florent-lamiraux I don't understand why this was parameterized before. Do you know why ?

**Comment by florent-lamiraux** [comment]
I do not remember precisely. Commit 4a28bcd in hpp-constraints sets default comparison type to `Equality` if nothing is provided.

The problem is that method `Implicit::create` sets comparison type to EqualToZero if nothing is provided. I think we should change that in hpp-constraints.
We need to choose the defaut value. I would ne in favor of "Equality".

**Comment by jmirabel** [comment]
Instead of having a default value, we could:
- make the constructor always take a comparison type,
- add `createEquality` and `createEqualToZero` static methods in Implicit ?
This way, the caller code will be clearer.

**Comment by jmirabel** [comment]
Another solution is to make handling the enum by enabling more user-friendly operation like
- `Equality << EqualToZero << ...`,
- `Equality * 6`,
- `Equality * 3 << EqualToZero`.

**Comment by florent-lamiraux** [comment]
I like the solution with `operator<<` and `operator*`.
I can implement it if you want.

**Comment by jmirabel** [comment]
You can have a look at https://github.com/humanoid-path-planner/hpp-fcl/blob/28ca0e58e9d93fdb9accfea9151f194df241ad52/include/hpp/fcl/collision_data.h#L460

**Comment by florent-lamiraux** [comment]
I will request a pull in hpp-constraint to implement the above.

**Comment by jmirabel** [comment]
@florent-lamiraux this can be closed, can't it ?
