### ISSUE TITLE
ProblemSolver create method

### ISSUE THREAD

**Issue by jmirabel** [humanoid-path-planner/hpp-core#23]
# Problem 
 
There is an incompatibility between the ubuntu-12.04 and ubuntu-14.04 versions:
* In Ubuntu-12.04 version: in class, hpp::core::ProblemSolver, "create" member function does not exist and the constructor is public
* In Ubuntu-14.04 version: the member function "create" exists and the constructor is protected.

This means that package with a dependency to hpp-core needs 2 versions, for a very tiny issue.

# Possible fix

* Let the constructor "public with a warning.
* Put the method create also in 12.04 version.

**Comment by florent-lamiraux** [comment]
Thank you for reporting this issue.
The rationale is the following
  - ubuntu-12.04 branches are frozen to a working version compatible all across the various packages,
  - master is a stable version working under ubuntu-14.04,
  - devel is the development branch with latest modifications, but with possible temporary compatibility loss between packages.
  - ubuntu-14.04 is a deprecated branch that should disappear.
Does this clarify the issue ?
Of course the rationale exposed above can be suject to discussion.
