### ISSUE TITLE
Configurations should be checked when calling addGoalConfig and setInitialConfig

### ISSUE THREAD

**Issue by florent-lamiraux** [humanoid-path-planner/hpp-core#230]
https://github.com/humanoid-path-planner/hpp-core/blob/de75ab4fb702ee6860fc9432e935a4a746e5ffd8/src/problem-solver.cc#L469
If the input configuration does not correspond to the Lie group structure of the model (quaternions not normalized), pinocchio raises an assert. We should check normalization and throw an exception.

The same here:
https://github.com/humanoid-path-planner/hpp-core/blob/de75ab4fb702ee6860fc9432e935a4a746e5ffd8/src/problem-solver.cc#L459

**Comment by jmirabel** [comment]
I think this is done in hpp-corbaserver, isn't it ?

**Comment by jmirabel** [comment]
After double-checking, it is done in hpp-corbaserver.

**Comment by florent-lamiraux** [comment]
The problems seems to be that the tolerance in hpp-corbaserver is set to 1e-4 and to 1e-8 in pinocchio. That is why I get an assert.
I propose to update hpp-corbaserver to use 1e-8.
