### ISSUE TITLE
Fetching submodule fails with new Github security updates

### ISSUE THREAD

**Issue by tanguy-s** [humanoid-path-planner/hpp-core#256]
Hi, 

Cloning this repo fails with following error:
```
Cloning into '/__w/third-parties/hpp-core/hpp-core/cmake'...
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
fatal: clone of 'git://github.com/jrl-umi3218/jrl-cmakemodules.git' into submodule path '/__w/third-parties/hpp-core/hpp-core/cmake' failed
```

All git:// unauthenticated git protocols should be replaced either with git@github.com, https:// or ssh://. 

Do you plan on updating ? 

We need this fix for repos:
hpp-constraints, hpp-core, hpp-fcl, hpp-manipulation-urdf, hpp-manipulation, hpp-pinocchio and hpp-util. 

Thanks

**Comment by nim65s** [comment]
Hi,

Thanks for the report, I'll fix this on the devel branches.

**Comment by tanguy-s** [comment]
Great thank you. Weird however, it does seem to work again. I believe they rolled back.
