### ISSUE TITLE
Copy constructor of ConstraintSet

### ISSUE THREAD

**Issue by jmirabel** [humanoid-path-planner/hpp-core#26]
In the copy constructor of class `ConstraintSet`, the `ConfigProjector` is copied twice since it is both an element of the list `constraints_` and pointed by the member `configProjector_`.
A solution could be to use an iterator on the list `constraints_` instead of pointer to the `ConfigProjector`.

**Comment by florent-lamiraux** [comment]
@jmirabel,
It seems that commit 51232d2 fixes this issue, right ?

**Comment by jmirabel** [comment]
Yes, it should fix the issue.
