### ISSUE TITLE
Problem with no constraint results in SEGV

### ISSUE THREAD

**Issue by jmirabel** [humanoid-path-planner/hpp-core#290]
As of now, when initializing a `Problem`, it has no constraints by default.

The code is not robust to a problem with no constraints. E.g. in `Problem::checkProblem`
https://github.com/humanoid-path-planner/hpp-core/blob/7eb151a6df3dd091c88cf8acdfca4d5f5edcae78/src/problem.cc#L297

There are two possible solutions:
- change the default constraints to an empty `ConstraintSet`
- make the code robust to no constraints.

This is especially annoying when using the object oriented CORBA API.
```python
cl = Client()
# Build a robot as usual
cpp_robot = cl.problem.getProblem().robot()
cpp_problem = cl.problem.createProblem(cpp_robot)\
cpp_problem.setInitConfig(q_init)
cpp_problem.addGoalConfig(q_goal)
# cpp_problem.setConstraints(...) # Not possible because one cannot easily create an empty constraint set.
roadmap = cl.problem.createRoadmap(cpp_problem.getDistance(), cpp_robot)
planner = cl.problem.createPathPlanner("BiRRTPlanner", cpp_problem, roadmap)
planner.solve() # results in a SEGV.
```

**Comment by florent-lamiraux** [comment]
The first solution seems to me the simplest and best one.
