### ISSUE TITLE
Organize subfolders

### ISSUE THREAD

**Issue by pFernbach** [humanoid-path-planner/hpp-core#50]
Since pull request https://github.com/humanoid-path-planner/hpp-core/pull/43 there is a new "steering-method" subfolder. But the old steering-method files are still in the root folder.

I think we should move all the steering-method in this subfolder and add a "planner" and "path" subfolders.

**Comment by jmirabel** [comment]
That would make sense to me.

**Comment by florent-lamiraux** [comment]
I agree.
