### ISSUE TITLE
Interface for obstacle events

### ISSUE THREAD

**Issue by jmirabel** [humanoid-path-planner/hpp-core#62]
Currently, all the `ConfigValidation` and `PathValidation` have a `addObstacle` (and other) method even though only a few of the derived class make use of it. This is a bad design for two reasons:
- it does not make sense for a class like `JointBoundValidation` to this method,
- `ConfigValidation::addObstacle` is not pure virtual because some child classes do not need it. This means a programmer (it just happened to me) who implement a derived class won't have an error if if does not reimplement `addObstacle` (or make a mistake in its prototype).

It would be good to define an interface for classes who needs to know about obstacles. I would propose to name it `ObstacleEventHandler`. Any opinion on the name ?

**Comment by florent-lamiraux** [comment]
I agree with the reasoning.
I would call the class "ObstacleHandler". I do not like the word "event" in this context.

**Comment by jmirabel** [comment]
I thought of this. I did not like the fact that it suggests the class is handling obstacles.
I would say that class `Problem` handles obstacles and the other classes use them.

**Comment by florent-lamiraux** [comment]
skype ?

**Comment by jmirabel** [comment]
We agreed on `ObstacleUser`.

**Comment by florent-lamiraux** [comment]
Solved by https://github.com/humanoid-path-planner/hpp-core/pull/189
